config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about' ,to:'home#about'
  devise_for :users, path_names: {sign_in:'login', sign_out:'logout'}, :controller =>{
    :sessions      => "users/sessions",
    :registrations => "users/registrations"
  }
  match "books/search" => "books#search", :via => :post
  match "books/isbn" => "books#isbn", :via => :get
  match "books/not_found" => "books#not_found", :via => :get
  resources :books
  get '/books/:course/:number', to: 'subjects#show', as:'subject'
  post '/books/mail_send', to: 'subjects#mail_send'
  get '/lookup/quick_look', to:'lookup#quick_look'
  match '/lookup/process', to:'lookup#matchup',          via:'post'
  match '/lookup/process', to:'lookup#matchup',          via:'get'
  get '/lookup/result', to:'lookup#result'
  post '/lookup/result', to:'lookup#result'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :relationships
  has_many :users, through: :relationships
  validates :course, presence: true, on: :isbn
  validates :number, presence: true
  validates :price, presence: true

  def self.search(search)
    if search.present?
      where('isbn LIKE ?', "%#{search}%")
    else
      where(true)
    end
  end



  def self.api_search(isbn)
        search_result = HTTParty.get("https://www.googleapis.com/books/v1/volumes?q=isbn:#{isbn}")
        search_result_json = JSON.parse(search_result.body)
        check = search_result_json['totalItems']
        logger.debug check
        if check != 0
          logger.debug 'pass1'
          title = search_result_json['items'][0]['volumeInfo']['title']
          subtitle = search_result_json['items'][0]['volumeInfo']['subtitle'] unless !subtitle.nil?
          author = search_result_json['items'][0]['volumeInfo']['authors'] unless !author.nil?
            if !author.nil?
              author[0] = author[0]+' '
              author = author.join("")
            end
          publisher = search_result_json['items'][0]['volumeInfo']['publisher'] unless !publisher.nil?
          pub_date = search_result_json['items'][0]['volumeInfo']['publishedDate'] unless !pub_date.nil?
          thumbnail = search_result_json['items'][0]['volumeInfo']['imageLinks']['thumbnail'] unless !thumbnail.nil?
        else
          logger.debug 'pass2'
          title = nil
          subtitle = nil
          author = nil
          publisher = nil
          pub_date = nil
          thumbnail = nil
        end
        return title, subtitle, author, publisher, pub_date, thumbnail
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @books = Book.search(params[:search])
    @book_sort = Book.all.sort_by{|m| m.course}
    store = Array.new
    @tstore = Array.new
    @book_sort.each do |a|
      if store.include?"#{a.course},#{a.number}"
      else
        @tstore << a
        @store =  @tstore.sort_by{|m| [m.course, m.number]}
      end
      store << "#{a.course},#{a.number}"
    end
  end

  def show
  end

  def new
    @book = Book.new
    @books = Array.new(3){Book.new}
  end

  def edit
  end

  def search
    @book = Book.new(book_params)
    @book.isbn = book_params[:isbn].sub('-', '')
    logger.debug @book.isbn
    @book.isbn = book_params[:isbn].delete(' ')
    @book.isbn = book_params[:isbn].sub('-', '').delete(' ')
    logger.debug @book.isbn
    if !@book.isbn.nil?
        stock = Book.api_search(@book.isbn)
    end
      if stock[0].nil?
        redirect_to books_not_found_path
      else
      redirect_to books_isbn_path(course: '', number: '', isbn: @book.isbn, title: stock[0], subtitle: stock[1], author: stock[2], publisher: stock[3], pub_date: stock[4], thumbnail: stock[5])
      end
  end

  def isbn
    @book = Book.new(isbn: params[:isbn], title: params[:title], subtitle: params[:subtitle], author: params[:author], publisher: params[:publisher], pub_date: params[:pub_date], thumbnail: params[:thumbnail])
    logger.debug @book.isbn
    logger.debug params
  end

  def not_found
  end

  def create
    @user = current_user
    respond_to do |format|
      if !book_params[:course].empty? && !book_params[:number].empty? && !book_params[:price].empty?
        @user.books.create(book_params)
        format.html { redirect_to books_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { redirect_to books_isbn_path(book_params)}
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:course, :number, :isbn, :title, :subtitle, :author, :publisher, :pub_date, :price, :comment, :condition, :professor, :thumbnail)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<section id="login">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
         <div class="form-wrap">
          <h1 style="font-size: 34px;">Please Enter isbn of Your Book!</h1>
          <%= form_for @book, :url => {:action=> "search"} do |f| %>
                <p><div class="center">
                <h1 style="padding-bottom:0px; font-size:25px;">isbn:</h1><%= f.text_field :isbn, class: "form-control", placeholder:"1234567890"%>
                Look for isbn number?  <%=link_to "Go to isbn website!", 'http://www.isbnsearch.org/', :target => "_blank"  %> </div></p>
            <div class="actions center">
              <%= f.submit class: 'btn btn-custom'  %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="center">
  <section id="login" style="padding:10px;">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="form-wrap">
            <% if !@store.nil? %>
              <% @store.each_with_index do |b, i|%>
                <% if i != 0 %>
                    <% if !@store[0..i-1].map(&:course).include?"#{b.course}"%>
                      <h1 style="font-size: 34px;"><%= b.course %></h1>
                    <% end %>
                <% else %>
                    <h1 style="font-size: 34px;"><%= b.course %></h1>
                <% end %>
                <%=link_to subject_path(b.course,b.number) do %>
                  <div class="users" style="color:black;">
                    <h4><%="#{b.course} #{b.number}" %></h4>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/books/isbn.html.erb
<section id="login">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="form-wrap">
            <h1>Is this a Book You Are looking for?</h1>
          <%= form_for(@book) do |f| %>
            <div style="float: left; margin-right:80px; margin-left:20px; margin-bottom:20px;">
              <%= image_tag @book.thumbnail, :size => "180x260" %>
            </div>
                <p style="margin-left: 80px">
                  <%= f.hidden_field :title, :value => @book.title %>Title: <%= @book.title %><br/>

                  <% if !@book.subtitle.nil? %>
                    <% if @book.subtitle == '' %>
                    <% else %>
                      <%= f.hidden_field :subtitle, :value => @book.subtitle %>
                      <% if !@book.subtitle.nil? %> Subtitle: <%= @book.subtitle %><br/> <%end%>
                    <% end %>
                  <% else %>
                    <%= f.hidden_field :subtitle, :value => '' %>
                  <%end%>

                  <% if !@book.author.nil? %>
                    <% if @book.author == '' %>
                    <% else %>
                      <%= f.hidden_field :author, :value => @book.author %>
                      <% if !@book.author.nil? %> author: <%= @book.author %><br/> <%end%>
                    <% end %>
                  <% else %>
                    <%= f.hidden_field :author, :value => '' %>
                  <%end%>

                  <% if !@book.publisher.nil? %>
                    <% if @book.publisher == '' %>
                    <% else %>
                      <%= f.hidden_field :publisher, :value => @book.publisher %>
                      <% if !@book.publisher.nil? %> publisher: <%= @book.publisher %><br/> <%end%>
                    <% end %>
                  <% else %>
                    <%= f.hidden_field :publisher, :value => '' %>
                  <%end%>

                  <% if !@book.pub_date.nil? %>
                    <% if @book.pub_date == '' %>
                    <% else %>
                      <%= f.hidden_field :pub_date, :value => @book.pub_date %>
                      <% if !@book.pub_date.nil? %> pub_date: <%= @book.pub_date %><br/> <%end%>
                    <% end %>
                  <% else %>
                    <%= f.hidden_field :pub_date, :value => '' %>
                  <%end%>
                  <%= f.hidden_field :isbn, :value => @book.isbn %>
                  <%= f.hidden_field :thumbnail, :value => @book.thumbnail %>
                </p>
                <div style="clear: both;">
                  <%=  f.label :course, class: "required"%>
                  <%=  f.text_field :course, class: "form-control", placeholder:"Business" %><br>

                  <%=  f.label :number, class: "required" %>
                  <%=  f.number_field :number, class: "form-control", placeholder:"101" %><br>

                  <%=  f.label :professor %>
                  <%=  f.text_field :professor, class: "form-control",placeholder:"Andrew Abeboi"  %><br>

                  <%=  f.label :price, class: "required" %>
                  <%=  f.number_field :price, class: "form-control", placeholder: "$" %><br>

                  <%=  f.label :comment %>
                  <%=  f.text_field :comment, class: "form-control", placeholder:"Things to note"  %><br>

                  <%=  f.label :condition %>
                  <%=  f.select :condition, [['Condition',nil], 'New', 'Almost New', 'Dirty','Very Dirty'], class: "form-control" %><br>
                  <div class="actions center" style="margin-top:10px;">
                    <%= f.submit "Register to sell", class:'btn btn-custom'%>
                  </div>
                </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/not_found.html.erb
<h1>sorry we could not find the book matched to isbn yo typed...</h1>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @book.course %>
</p>

<p>
  <strong>Number:</strong>
  <%= @book.number %>
</p>

<p>
  <strong>Number of Stock</strong>
  <%= @book.count %>
</p>



<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>