config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about' ,to:'home#about'
  devise_for :users, path_names: {sign_in:'login', sign_out:'logout'}, :controller =>{
    :sessions      => "users/sessions",
    :registrations => "users/registrations"
  }
  match "books/search" => "books#search", :via => :post
  match "books/isbn" => "books#isbn", :via => :get
  match "books/not_found" => "books#not_found", :via => :get
  resources :books
  get '/books/:course/:number', to: 'subjects#show', as:'subject'
  post '/books/mail_send', to: 'subjects#mail_send'
  get '/lookup/quick_look', to:'lookup#quick_look'
  match '/lookup/process', to:'lookup#matchup',          via:'post'
  match '/lookup/process', to:'lookup#matchup',          via:'get'
  get '/lookup/result', to:'lookup#result'
  post '/lookup/result', to:'lookup#result'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TextbookExchange</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top nav-opa">
      <div class="container">
        <%= link_to "TextbookExchange", root_path, id: "logo" %>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to "About",    about_path %></li>
              <li><%= link_to "Sell",    new_book_path  %></li>
              <li><%= link_to 'Buy', books_path %></li>
              <li><%= link_to 'Bundle', lookup_quick_look_path %></li>
              <% if user_signed_in? %>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "SingUp", new_user_registration_path %></li>
                <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
            </ul>
        </div>
    </nav>
  <%= yield %>
</body>
</html>